---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s3api
spec:
  rules:
  - http:
      paths:
      - path: /v1/s3
        backend:
          serviceName: s3api
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s3api
  labels:
    app: s3api
    tier: api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
    prometheus.io/path:   '/v1/s3/metrics'
spec:
  selector:
    app: s3api
    tier: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3api
  labels:
    app: s3api
    tier: api
spec:
  selector:
    matchLabels:
      app: s3api
      tier: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: s3api
        tier: api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: s3api
        image: hub.docker.com/yaleits/s3api
        volumeMounts:
        - name: s3api-config
          mountPath: "/app/config"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /v1/s3/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: s3api-config
        secret:
          secretName: s3-api-config-json
        # envFrom:
        #   - configMapRef:
        #       name: s3api-config
        #   - secretRef:
        #       name: s3api-secrets
